package com.xtower.game;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 Game g; public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setSystemUiVisibility(5894);g=new Game();setContentView(g);}
 class Game extends View{
  Paint p=new Paint(1);Random r=new Random();int floor=1,maxFloor=1,hp=100,maxHp=100,atk=5,def=3,ehp=40,emax=40,eatk=8,edef=2,extra=0;boolean won=false,chest=false;String mode="전투",log="X탑에 진입했습니다.";ArrayList<Item> bag=new ArrayList<>(),stash=new ArrayList<>();HashMap<Integer,Prisoner> jail=new HashMap<>();String[] names={"아이린","이리스","마를렌","노에","카렌","비비안","루나","에델"};String[] items={"입맞춤 회복약","옷 찢는 단도","치마 가르개","가슴받이 방패","쇠코르셋","손으로 먹이는 빵","심문 등잔","금기 서책","밀어붙이는 창","눈가리개 투구","찢어진 팬티","끈 브라","이름표 목줄","은 수갑","결박 밧줄","재갈","실크 안대","발목 사슬","발목 고리","가죽 하네스"};
  class Item{String n;int a,d,h,enh,mod;Item(String n){this.n=n;a=r.nextInt(8);d=r.nextInt(6);h=r.nextInt(9);}}
  class Prisoner{String n;ArrayList<Item>b=new ArrayList<>();Prisoner(String n){this.n=n;}}
  Game(){super(MainActivity.this);p.setTypeface(Typeface.DEFAULT_BOLD);load();spawn();}
  void spawn(){long m=1L<<Math.min(floor-1,20);emax=(int)Math.min(500000000,40*m);ehp=emax;eatk=(int)Math.min(500000000,8*m);edef=(int)Math.min(500000000,2*m);won=false;chest=false;}
  void stats(){atk=5;def=3;maxHp=100;for(Item i:bag){atk+=i.a+i.enh;def+=i.d+i.enh;maxHp+=i.h;}for(Prisoner q:jail.values())for(Item i:q.b){atk+=i.a+i.enh;def+=i.d+i.enh;maxHp+=i.h;}hp=Math.min(hp,maxHp);}
  void text(Canvas c,String s,float x,float y,float z,int col){p.setTextSize(z);p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);}void box(Canvas c,float l,float t,float rr,float b,int col){p.setColor(col);c.drawRoundRect(l,t,rr,b,24,24,p);}
  protected void onDraw(Canvas c){super.onDraw(c);stats();c.drawColor(Color.rgb(8,7,12));int w=getWidth(),h=getHeight();text(c,"X탑",28,60,42,Color.WHITE);text(c,"FLOOR "+floor+"   HP "+hp+"/"+maxHp+"   힘 "+atk+"   방어 "+def,28,96,18,0xffcfc5d5);if(mode.equals("전투")){text(c,names[(floor-1)%names.length]+"  HP "+ehp+"/"+emax,28,145,26,Color.WHITE);box(c,28,165,w-28,h-300,0xff151822);text(c,"전투 이미지 / 캐릭터 영역",52,220,20,0xff80778a);box(c,28,h-270,w-28,h-200,chest?0xffa56b28:0xff7546ee);text(c,chest?"보상 상자 열기":"공격",52,h-225,25,Color.WHITE);String[] bs={"다시","↓","↑","배낭","대장간","감옥"};float bw=(w-70)/6f;for(int i=0;i<6;i++){box(c,28+i*(bw+2),h-185,28+i*(bw+2)+bw,h-125,0xff292333);text(c,bs[i],36+i*(bw+2),h-147,15,Color.WHITE);}}else{box(c,24,130,w-24,h-130,0xff17141e);text(c,"X TOWER SYSTEM · "+mode,40,180,28,Color.WHITE);if(mode.equals("배낭")){text(c,"5열 기본 10칸 + 확장 "+extra+"칸",40,225,18,0xffc5b9ce);int y=265;for(Item i:bag){text(c,"장착 · "+i.n+"  힘+"+i.a+" 방+"+i.d+" 체+"+i.h+" 강화+"+i.enh,40,y,15,Color.WHITE);y+=25;}for(Item i:stash){text(c,"주머니 · "+i.n+"  보정 "+i.mod+"%",40,y,15,0xffd7a6c0);y+=25;}}else if(mode.equals("대장간")){text(c,"터치: 강화 10% / 합성 1% / 분해 10~100%",40,225,17,Color.WHITE);text(c,"주머니 아이템: "+stash.size()+"개",40,260,17,0xffc5b9ce);}else{text(c,"포획 확률 1% · 포획자 장비 능력치 합산",40,225,17,Color.WHITE);int y=265;for(Integer f:jail.keySet()){Prisoner q=jail.get(f);text(c,f+"층 · "+q.n+" · 장비 "+q.b.size(),40,y,17,Color.WHITE);y+=30;}}box(c,24,h-105,w-24,h-45,0xff31283c);text(c,"전투로 돌아가기",48,h-66,20,Color.WHITE);}text(c,log,28,h-18,15,0xffc8bdcc);}
  public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=1)return true;float x=e.getX(),y=e.getY();int w=getWidth(),h=getHeight();if(!mode.equals("전투")){if(y>h-120){mode="전투";invalidate();return true;}if(mode.equals("배낭")){if(!stash.isEmpty()){Item i=stash.remove(0);bag.add(i);log=i.n+" 장착";}}else if(mode.equals("대장간")){forge();}else if(mode.equals("감옥")){if(!jail.isEmpty()&&!stash.isEmpty()){Prisoner q=jail.values().iterator().next();q.b.add(stash.remove(0));log=q.n+"에게 장비 지급";}}save();invalidate();return true;}if(y>h-285&&y<h-190){if(chest){reward();}else attack();invalidate();return true;}if(y>h-190&&y<h-115){float bw=(w-70)/6f;int i=Math.max(0,Math.min(5,(int)((x-28)/(bw+2))));if(i==0&&won){hp=maxHp;spawn();log="같은 층 재전투";}else if(i==1&&floor>1){floor--;hp=maxHp;spawn();log="아래층 이동";}else if(i==2&&floor<maxFloor){floor++;hp=maxHp;spawn();log="위층 이동";}else if(i==3)mode="배낭";else if(i==4)mode="대장간";else if(i==5)mode="감옥";save();invalidate();return true;}if(won){log=names[(floor-1)%names.length]+" : "+new String[]{"머리 만지지 마.","가까이 오지 마.","손 치워.","끝까지 가 봐."}[r.nextInt(4)];invalidate();}return true;}
  void attack(){stats();int dmg=Math.max(1,atk-edef);ehp=Math.max(0,ehp-dmg);log=new String[]{"타격","강타","연타"}[r.nextInt(3)]+" -"+dmg;if(ehp<=0){won=true;chest=true;maxFloor=Math.max(maxFloor,floor+1);log="격파. 보상 상자를 여십시오.";}else{int d=Math.max(1,eatk-def);hp=Math.max(0,hp-d);if(hp<=0){stash.clear();floor=1;hp=maxHp;spawn();log="사망. 주머니 전리품 소실, 1층 복귀.";}}save();}
  void reward(){int[] m={-50,-40,-30,-20,-10,10,20,30,40,50};int mod=m[r.nextInt(m.length)];int n=1+r.nextInt(2)+(floor>=4?1:0);for(int k=0;k<n;k++){Item i=new Item(items[r.nextInt(items.length)]);i.mod=mod;stash.add(i);}if(!jail.containsKey(floor)&&r.nextInt(100)==0){jail.put(floor,new Prisoner(names[(floor-1)%names.length]));log="룰렛 "+mod+"% · 전리품 "+n+"개 · 포획 성공!";}else log="룰렛 "+mod+"% · 전리품 "+n+"개";chest=false;mode="배낭";save();}
  void forge(){if(stash.isEmpty()){log="제물이 없습니다.";return;}Item target=bag.isEmpty()?null:bag.get(0);if(target==null){target=stash.remove(0);bag.add(target);log="대장간 대상 장착";return;}Item food=stash.remove(0);int roll=r.nextInt(100);if(roll<1){target.a+=food.a;target.d+=food.d;target.h+=food.h;log="합성 성공 1%";}else if(roll<11&&target.enh<10){target.enh++;log="강화 성공 +"+target.enh;}else{int count=Math.min(10,Math.max(1,stash.size()+1));if(r.nextInt(100)<count*10){extra++;log="분해 성공. 배낭 +1칸";}else log="강화/합성/분해 실패. 제물 소멸";}save();}
  void save(){try{JSONObject o=new JSONObject();o.put("floor",floor);o.put("max",maxFloor);o.put("hp",hp);o.put("extra",extra);getSharedPreferences("x",0).edit().putString("s",o.toString()).apply();}catch(Exception z){}}
  void load(){try{String z=getSharedPreferences("x",0).getString("s","");if(z.length()>0){JSONObject o=new JSONObject(z);floor=o.optInt("floor",1);maxFloor=o.optInt("max",1);hp=o.optInt("hp",100);extra=o.optInt("extra",0);}}catch(Exception z){}}
 }
}
